notifications:
  email: false
git:
  quiet: true
  depth: 1

env:
  global:
  - TERM=dumb
  - secure: hw6pdShvlvOYQE2N8qVUigZ3A06bj55LmOB786/B3zxWzwAa8mjfPo7jYD5eHTkiuUSpVKMhnr0MsKy//NJu+UIm2OqwZjhTMqYaiZx3a3mtontKgbcLsHJI7IyfQF3OqQVsvhoi+3yf8rfyysq4tnP+0RPlfqtYnrrNNolOBQRdaixQgACfzqYfkYM11EdInXZY6WZkfkIJHvmYhFJKB6D8LgEKdrY6q7W/KmPB9T37c2fcMxe/4aSaoHzFX3JPi6OLc3tT21Kv+XRQPYV7tp3XP67M6rGq2RKzXrKzLoYEjIU5d0pFbygmwE5YBdfn7j7C10rxAeFZ/UOXYJtCJW9ZojKkitwiDzUvo3Bu+Q3v0XDPE/hQ4RwC4zbmeT8DH2GnSSTNnAq+55ESbVXPGAo4FsW/PBlqBx4KlfOpjNbyBPeECGy1xYbOi547YqAYxkqVn3augp5OgZ/bNFRM80ib9k6lv81hFhBrC7Yp1b8GmO6XeUG0QZoOkKclO0DtzhM972uQiYL2Wb6i+Ll7cVeP6Oss+8VNENZTne2+weVVsl/tHFbjLI8mWaQmROqfVpekYl1UzJVx3iJQKSFiRTJlhXjnZYxabet+HPAggw0r40yWJUZRsRH3rFekBNmdjaVRQ+8nihdUOPS9bzCHYO/IUYuTrKDN7B3IJrFiVVU=

language: java
jdk: openjdk8
rvm: 2.6.4

addons:
  apt:
    update: true
    packages:
    - jq
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - unzip
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools

install: true
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null
- pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
- http --version --debug
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432

stages:
- test
- deploy

jobs:
  include:

  - stage: test
    jdk: openjdk8
    name: mvn
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -U >/dev/null
    - java -jar $TRAVIS_BUILD_DIR/target/*-all.jar &
    - wait_for 8080
    - |
      echo '[
        {
          "type":"CounterCreated",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "counterName": "hello 1"
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 2
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 3
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max"
        },
        {
          "type":"CounterSuspended",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "reason": "because!"
        }
      ]' | http post :8080/events/collection

    - http :8080/events/00000000-0000-0000-0000-000000000001/collection Accept:application/json
    - http :8080/events/00000000-0000-0000-0000-000000000000 Accept:application/json
    - http :8080/events
    - http delete :8080/events

    - http :8080/counter
    - http post :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterCreated counterName=hi
    - http put :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterIncremented by=travis withValue=1
    - http put :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterIncremented withValue=2
    - http delete :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterSuspended reason="just because I can"
    - http :8080/counter/00000000-0000-0000-0000-000000000000
    - http :8080/counter
    - http delete :8080/events
    - http :8080/counter/00000000-0000-0000-0000-000000000000
    - stop_any 80 8080

  - stage: test
    jdk: openjdk8
    name: display-property-updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    jdk: openjdk11
    name: test jdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw
    - java -jar $TRAVIS_BUILD_DIR/target/*-all.jar &
    - wait_for 8080
    - |
      echo '[
        {
          "type":"CounterCreated",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "counterName": "hello 1"
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 2
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 3
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max"
        },
        {
          "type":"CounterSuspended",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "reason": "because!"
        }
      ]' | http post :8080/events/collection

    - http :8080/events/00000000-0000-0000-0000-000000000001/collection Accept:application/json
    - http :8080/events/00000000-0000-0000-0000-000000000000 Accept:application/json
    - http :8080/events
    - http delete :8080/events

    - http :8080/counter
    - http post :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterCreated counterName=hi
    - http put :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterIncremented by=travis withValue=1
    - http put :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterIncremented withValue=2
    - http delete :8080/counter aggregateId=00000000-0000-0000-0000-000000000000 type=CounterSuspended reason="just because I can"
    - http :8080/counter/00000000-0000-0000-0000-000000000000
    - http :8080/counter
    - http delete :8080/events
    - http :8080/counter/00000000-0000-0000-0000-000000000000
    - stop_any 80 8080

  - stage: test
    jdk: openjdk11
    name: display-property-updates jdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: deploy
    jdk: openjdk11
    rvm: 2.6.4
    name: GitHub release and GitHub pages deployment
    script: skip
    if: branch = "master" AND type NOT IN (pull_request)
    before_deploy:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
    - set -e
    - ./mvnw exec:exec
    - ./mvnw -Pjekyll-search
    - ./mvnw -Pjekyll-build
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      local-dir: docs/_site
      target_branch: gh-pages
      on:
        branch: master
        condition: "$TRAVIS_PULL_REQUEST = false"

cache:
  pip: true
  bundler: true
  packages: true
  directories:
  - "~/.m2"
