notifications:
  email: false
git:
  quiet: true
  depth: 1

env:
  global:
  - TERM=dumb
  - secure: hw6pdShvlvOYQE2N8qVUigZ3A06bj55LmOB786/B3zxWzwAa8mjfPo7jYD5eHTkiuUSpVKMhnr0MsKy//NJu+UIm2OqwZjhTMqYaiZx3a3mtontKgbcLsHJI7IyfQF3OqQVsvhoi+3yf8rfyysq4tnP+0RPlfqtYnrrNNolOBQRdaixQgACfzqYfkYM11EdInXZY6WZkfkIJHvmYhFJKB6D8LgEKdrY6q7W/KmPB9T37c2fcMxe/4aSaoHzFX3JPi6OLc3tT21Kv+XRQPYV7tp3XP67M6rGq2RKzXrKzLoYEjIU5d0pFbygmwE5YBdfn7j7C10rxAeFZ/UOXYJtCJW9ZojKkitwiDzUvo3Bu+Q3v0XDPE/hQ4RwC4zbmeT8DH2GnSSTNnAq+55ESbVXPGAo4FsW/PBlqBx4KlfOpjNbyBPeECGy1xYbOi547YqAYxkqVn3augp5OgZ/bNFRM80ib9k6lv81hFhBrC7Yp1b8GmO6XeUG0QZoOkKclO0DtzhM972uQiYL2Wb6i+Ll7cVeP6Oss+8VNENZTne2+weVVsl/tHFbjLI8mWaQmROqfVpekYl1UzJVx3iJQKSFiRTJlhXjnZYxabet+HPAggw0r40yWJUZRsRH3rFekBNmdjaVRQ+8nihdUOPS9bzCHYO/IUYuTrKDN7B3IJrFiVVU=

language: java
jdk: openjdk11
rvm: 2.6.4

addons:
  apt:
    update: true
    packages:
    - jq
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - unzip
    - httpie

install: true
before_install:
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432

stages:
- test
- deploy

jobs:
  include:

  - stage: test
    name: integration test
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw
    - java -jar $TRAVIS_BUILD_DIR/target/*-all.jar &
    - wait_for 8080
    - |
      echo '[
        {
          "type":"CounterCreated",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "counterName": "hello 1"
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 2
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max",
          "withValue": 3
        },
        {
          "type":"CounterIncremented",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "by": "max"
        },
        {
          "type":"CounterSuspended",
          "aggregateId": "00000000-0000-0000-0000-000000000000",
          "reason": "because!"
        }
      ]' | http post :8080/events/collection

    - http :8080/events/00000000-0000-0000-0000-000000000001/collection Accept:application/json
    - http :8080/events/00000000-0000-0000-0000-000000000000            Accept:application/json
    - http :8080/events
    - http delete :8080/events

    - http :8080/counter
    - http post   :8080/counter aggregateId=0-0-0-0-0 type=CounterCreated counterName=hi
    - http put    :8080/counter aggregateId=0-0-0-0-0 type=CounterIncremented by=travis withValue=1
    - http put    :8080/counter aggregateId=0-0-0-0-0 type=CounterIncremented withValue=2
    - http delete :8080/counter aggregateId=0-0-0-0-0 type=CounterSuspended reason="just because I can"
    - http get    :8080/counter/0-0-0-0-0
    - http get    :8080/counter
    - http delete :8080/events
    - http get    :8080/counter/0-0-0-0-0
    - stop_any 80 8080

cache:
  packages: true
  directories:
  - "~/.m2"
