# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EventStore
email: daggerok@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Building File based event-store with Jackson JSON
  Serialisation and Deserialization, Jersey REST API
  uses Netty runtime and Weld CDI
baseurl: /jersey-netty-cdi-jackson-file-eventstore/ # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: daggerok
github_username:  daggerok

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

search_enabled: true
heading_anchors: true
footer_content: >-
  Jersey Netty CDI Jackson File based EventStore.
  Copyright &copy; 2019 Maksim Kostromin.
#footer_content: >-
#  Jersey Netty CDI Jackson File based EventStore.
#  Copyright &copy; 2019 Maksim Kostromin. That awesome jekyll theme was taken from
#  <a href=\"https://github.com/pmarsceill/just-the-docs/\">Just The Docs</a> repository.
color_scheme: "dark"
